name: Stats

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  stat:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10, 12, 14, 16, 18, 20]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run stats
        id: stats
        run: |
          version=$(node -v | sed "s/v//g" | sed "s/\./_/g")
          ./run.sh > stats-$version.md

  commit:
    runs-on: ubuntu-latest
    needs: [stat]

    steps:
      - uses: actions/checkout@v3

      - name: Create Result files
        run: |
          cat ./stats-*.md > RESULTS.md;
          cat RESULTS.md

      # - name: commit and push updated results
      #   uses: github-actions-x/commit@v2.9
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     push-branch: 'main'
      #     commit-message: 'chore(v20.x): update benchmark results'
      #     force-add: 'true'
      #     rebase: 'true'
      #     files: RESULTS*.md v20/*
      #     name: Github Actions
