name: Stats

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  stat:
    runs-on: ubuntu-latest
    outputs:
      STATS_v20: ${{ steps.stat.outputs.STATS_v20 }}
      STATS_v18: ${{ steps.stat.outputs.STATS_v18 }}
      STATS_v16: ${{ steps.stat.outputs.STATS_v16 }}
      STATS_v14: ${{ steps.stat.outputs.STATS_v14 }}
      STATS_v12: ${{ steps.stat.outputs.STATS_v12 }}
      STATS_v10: ${{ steps.stat.outputs.STATS_v10 }}

    strategy:
      matrix:
        node-version: [10, 12, 14, 16, 18, 20]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: |
          sudo apt update -y
          sudo apt install -y wget
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.16.1/hyperfine_1.16.1_amd64.deb
          sudo dpkg -i hyperfine_1.16.1_amd64.deb

      - name: Run stats
        id: stat
        run: |
          version=$(node -v | sed "s/\..*$//")
          ./run.sh > ./stats.md
          result=$(cat ./stats.md)
          # https://trstringer.com/github-actions-multiline-strings/
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          result="${result//$'`'/'\`'}"
          echo "::set-output name=STATS_$version::$result"

  commit:
    runs-on: ubuntu-latest
    needs: [stat]

    steps:
      - uses: actions/checkout@v3

      - name: Create Result files
        run: |
          echo "# Node.js stats" > README.md
          echo "```${{ needs.stat.outputs.STATS_v20 }}```" >> README.md
          echo "```${{ needs.stat.outputs.STATS_v18 }}```" >> README.md
          echo "```${{ needs.stat.outputs.STATS_v16 }}```" >> README.md
          echo "```${{ needs.stat.outputs.STATS_v14 }}```" >> README.md
          echo "```${{ needs.stat.outputs.STATS_v12 }}```" >> README.md
          echo "```${{ needs.stat.outputs.STATS_v10 }}```" >> README.md

      - name: commit and push updated results
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'doc: update stats'
          force-add: 'true'
          rebase: 'true'
          files: README.md
          name: Github Actions
